### ISSUE TITLE
Feat: Implement Parking Lots Screen

### ISSUE THREAD

**Issue by kirpnlbr** [kirpnlbr/spot-on#3]
# Feat: Implement Parking Lots Screen
## Description
Create the screen showing available parking lots with search functionality

## Wireframe
<img width="345" alt="image" src="https://github.com/user-attachments/assets/574d8fd4-ed0e-4a24-b61a-da66ba7ffb66">

## Tasks
1. Create ParkingLotsScreen Component:
   - [x] Create screen layout
   - [ ] Add header with back button
   - [x] Create lot list container
   - [x] Add lot card component

2. Implement Lot Listing:
   - [x] Create lot card design
   - [x] Show distance and available spots
   - [x] Add click handling
   - [x] Implement scroll behavior

3. Add Search Functionality:
   - [x] Create search input component
