### ISSUE TITLE
Feat: Implement Parking Grid Screen

### ISSUE THREAD

**Issue by kirpnlbr** [kirpnlbr/spot-on#5]
# Feat: Implement Parking Grid Screen

## Wireframe
<img width="340" alt="image" src="https://github.com/user-attachments/assets/a6568a00-f49e-498e-ab04-cea6591341b8">

## Tasks
Setup Basic Structure:
- [ ] Create ParkingGridPage component
- [ ] Add mock data for spots
- [ ] Create basic layout containers

Create Grid Layout:
- [ ] Design spot grid structure
- [ ] Map through parking spots
- [ ] Style individual spots

Add Functionality:
- [ ] Display spot status (available/occupied)
- [ ] Handle spot selection
- [ ] Show spot details

Add UI Elements:
- [ ] Add header with lot name
- [ ] Add availability stats
- [ ] Add navigation elements

Connect with ParkingLotsPage:
- [ ] Receive selected lot data
- [ ] Display correct lot information
- [ ] Handle navigation
